// coding: utf-8

// ─── A1: базові дієслова, найпоширеніші на A1 за Goethe ───
window.WORDS_A1 = [
    { infinitiv: 'sein', praeteritum: 'war', perfekt: 'ist gewesen', uk: 'бути', en: 'to be', hu: 'lenni' },
    { infinitiv: 'haben', praeteritum: 'hatte', perfekt: 'hat gehabt', uk: 'мати', en: 'to have', hu: 'bírni' },
    { infinitiv: 'werden', praeteritum: 'wurde', perfekt: 'ist geworden', uk: 'ставати', en: 'to become', hu: 'válni' },
    { infinitiv: 'gehen', praeteritum: 'ging', perfekt: 'ist gegangen', uk: 'йти', en: 'to go', hu: 'menni' },
    { infinitiv: 'kommen', praeteritum: 'kam', perfekt: 'ist gekommen', uk: 'приходити', en: 'to come', hu: 'jönni' },
    { infinitiv: 'sehen', praeteritum: 'sah', perfekt: 'hat gesehen', uk: 'бачити', en: 'to see', hu: 'látni' },
    { infinitiv: 'geben', praeteritum: 'gab', perfekt: 'hat gegeben', uk: 'давати', en: 'to give', hu: 'adni' },
    { infinitiv: 'nehmen', praeteritum: 'nahm', perfekt: 'hat genommen', uk: 'брати', en: 'to take', hu: 'venni' },
    { infinitiv: 'fahren', praeteritum: 'fuhr', perfekt: 'ist gefahren', uk: 'їхати', en: 'to drive', hu: 'utazni' },
    { infinitiv: 'laufen', praeteritum: 'lief', perfekt: 'ist gelaufen', uk: 'бігти', en: 'to run', hu: 'futni' },
    { infinitiv: 'essen', praeteritum: 'aß', perfekt: 'hat gegessen', uk: 'їсти', en: 'to eat', hu: 'enni' },
    { infinitiv: 'trinken', praeteritum: 'trank', perfekt: 'hat getrunken', uk: 'пити', en: 'to drink', hu: 'inni' },
    { infinitiv: 'schlafen', praeteritum: 'schlief', perfekt: 'hat geschlafen', uk: 'спати', en: 'to sleep', hu: 'aludni' },
    { infinitiv: 'sprechen', praeteritum: 'sprach', perfekt: 'hat gesprochen', uk: 'говорити', en: 'to speak', hu: 'beszélni' },
    { infinitiv: 'schreiben', praeteritum: 'schrieb', perfekt: 'hat geschrieben', uk: 'писати', en: 'to write', hu: 'írni' },
    { infinitiv: 'lesen', praeteritum: 'las', perfekt: 'hat gelesen', uk: 'читати', en: 'to read', hu: 'olvasni' },
    { infinitiv: 'finden', praeteritum: 'fand', perfekt: 'hat gefunden', uk: 'знаходити', en: 'to find', hu: 'találni' },
    { infinitiv: 'helfen', praeteritum: 'half', perfekt: 'hat geholfen', uk: 'допомагати', en: 'to help', hu: 'segíteni' },
    { infinitiv: 'stehen', praeteritum: 'stand', perfekt: 'hat gestanden', uk: 'стояти', en: 'to stand', hu: 'állni' },
    { infinitiv: 'liegen', praeteritum: 'lag', perfekt: 'hat gelegen', uk: 'лежати', en: 'to lie', hu: 'feküdni' },
    { infinitiv: 'sitzen', praeteritum: 'saß', perfekt: 'hat gesessen', uk: 'сидіти', en: 'to sit', hu: 'ülni' },
    { infinitiv: 'rufen', praeteritum: 'rief', perfekt: 'hat gerufen', uk: 'кликати', en: 'to call', hu: 'hívni' },
    { infinitiv: 'bringen', praeteritum: 'brachte', perfekt: 'hat gebracht', uk: 'приносити', en: 'to bring', hu: 'hozni' },
    { infinitiv: 'denken', praeteritum: 'dachte', perfekt: 'hat gedacht', uk: 'думати', en: 'to think', hu: 'gondolni' },
    { infinitiv: 'kennen', praeteritum: 'kannte', perfekt: 'hat gekannt', uk: 'знати (людину)', en: 'to know', hu: 'ismerni' },
    { infinitiv: 'wissen', praeteritum: 'wusste', perfekt: 'hat gewusst', uk: 'знати (факт)', en: 'to know', hu: 'tudni' },
    { infinitiv: 'treffen', praeteritum: 'traf', perfekt: 'hat getroffen', uk: 'зустрічати', en: 'to meet', hu: 'találkozni' },
    { infinitiv: 'halten', praeteritum: 'hielt', perfekt: 'hat gehalten', uk: 'тримати', en: 'to hold', hu: 'tartani' },
    { infinitiv: 'fallen', praeteritum: 'fiel', perfekt: 'ist gefallen', uk: 'падати', en: 'to fall', hu: 'esni' },
    { infinitiv: 'tragen', praeteritum: 'trug', perfekt: 'hat getragen', uk: 'нести/носити', en: 'to carry/wear', hu: 'hordani' },
    { infinitiv: 'schließen', praeteritum: 'schloss', perfekt: 'hat geschlossen', uk: 'закривати', en: 'to close', hu: 'zárni' },
    { infinitiv: 'öffnen', praeteritum: 'öffnete', perfekt: 'hat geöffnet', uk: 'відкривати', en: 'to open', hu: 'kinyitni' },
    { infinitiv: 'kaufen', praeteritum: 'kaufte', perfekt: 'hat gekauft', uk: 'купувати', en: 'to buy', hu: 'venni/vásárolni' },
    { infinitiv: 'heißen', praeteritum: 'hieß', perfekt: 'hat geheißen', uk: 'звати(ся)', en: 'to be called', hu: 'hívni' },
    { infinitiv: 'beginnen', praeteritum: 'begann', perfekt: 'hat begonnen', uk: 'починати', en: 'to begin', hu: 'kezdeni' },
    { infinitiv: 'vergessen', praeteritum: 'vergaß', perfekt: 'hat vergessen', uk: 'забувати', en: 'to forget', hu: 'elfelejteni' },
    { infinitiv: 'verlieren', praeteritum: 'verlor', perfekt: 'hat verloren', uk: 'втрачати', en: 'to lose', hu: 'elveszteni' },
    { infinitiv: 'fliegen', praeteritum: 'flog', perfekt: 'ist geflogen', uk: 'літати', en: 'to fly', hu: 'repülni' },
    { infinitiv: 'schwimmen', praeteritum: 'schwamm', perfekt: 'ist geschwommen', uk: 'плавати', en: 'to swim', hu: 'úszni' },
    { infinitiv: 'schlagen', praeteritum: 'schlug', perfekt: 'hat geschlagen', uk: 'бити', en: 'to hit', hu: 'ütni' },
    { infinitiv: 'waschen', praeteritum: 'wusch', perfekt: 'hat gewaschen', uk: 'мити', en: 'to wash', hu: 'mosni' },
    { infinitiv: 'brechen', praeteritum: 'brach', perfekt: 'hat gebrochen', uk: 'ламати', en: 'to break', hu: 'törni' },
    { infinitiv: 'steigen', praeteritum: 'stieg', perfekt: 'ist gestiegen', uk: 'підніматися', en: 'to climb', hu: 'felmászni' },
    { infinitiv: 'einladen', praeteritum: 'lud ein', perfekt: 'hat eingeladen', uk: 'запрошувати', en: 'to invite', hu: 'meghívni' },
    { infinitiv: 'abfahren', praeteritum: 'fuhr ab', perfekt: 'ist abgefahren', uk: 'відїжджати', en: 'to depart', hu: 'elindulni' },
    { infinitiv: 'ankommen', praeteritum: 'kam an', perfekt: 'ist angekommen', uk: 'прибувати', en: 'to arrive', hu: 'megérkezni' },
    { infinitiv: 'anrufen', praeteritum: 'rief an', perfekt: 'hat angerufen', uk: 'телефонувати', en: 'to call', hu: 'telefonálni' },
    { infinitiv: 'aufstehen', praeteritum: 'stand auf', perfekt: 'ist aufgestanden', uk: 'вставати', en: 'to get up', hu: 'felkelni' },
    { infinitiv: 'sinken', praeteritum: 'sank', perfekt: 'ist gesunken', uk: 'тонути', en: 'to sink', hu: 'süllyedni' },
    { infinitiv: 'springen', praeteritum: 'sprang', perfekt: 'ist gesprungen', uk: 'стрибати', en: 'to jump', hu: 'ugrani' },
];

// ─── A2: розширений словник ───
window.WORDS_A2 = [
    { infinitiv: 'empfehlen', praeteritum: 'empfahl', perfekt: 'hat empfohlen', uk: 'рекомендувати', en: 'to recommend', hu: 'ajánlani' },
    { infinitiv: 'entscheiden', praeteritum: 'entschied', perfekt: 'hat entschieden', uk: 'вирішувати', en: 'to decide', hu: 'dönteni' },
    { infinitiv: 'erklären', praeteritum: 'erklärte', perfekt: 'hat erklärt', uk: 'пояснювати', en: 'to explain', hu: 'magyarázni' },
    { infinitiv: 'verstehen', praeteritum: 'verstand', perfekt: 'hat verstanden', uk: 'розуміти', en: 'to understand', hu: 'érteni' },
    { infinitiv: 'erzählen', praeteritum: 'erzählte', perfekt: 'hat erzählt', uk: 'розповідати', en: 'to tell', hu: 'mesélni' },
    { infinitiv: 'gefallen', praeteritum: 'gefiel', perfekt: 'hat gefallen', uk: 'подобатися', en: 'to please', hu: 'tetszeni' },
    { infinitiv: 'gewinnen', praeteritum: 'gewann', perfekt: 'hat gewonnen', uk: 'вигравати', en: 'to win', hu: 'nyerni' },
    { infinitiv: 'verlassen', praeteritum: 'verließ', perfekt: 'hat verlassen', uk: 'залишати', en: 'to leave', hu: 'elhagyni' },
    { infinitiv: 'erschrecken', praeteritum: 'erschrak', perfekt: 'ist erschrocken', uk: 'лякатися', en: 'to be scared', hu: 'megijedni' },
    { infinitiv: 'vorstellen', praeteritum: 'stellte vor', perfekt: 'hat vorgestellt', uk: 'представляти', en: 'to introduce', hu: 'bemutatni' },
    { infinitiv: 'bestellen', praeteritum: 'bestellte', perfekt: 'hat bestellt', uk: 'замовляти', en: 'to order', hu: 'rendelni' },
    { infinitiv: 'bezahlen', praeteritum: 'bezahlte', perfekt: 'hat bezahlt', uk: 'платити', en: 'to pay', hu: 'fizetni' },
    { infinitiv: 'besuchen', praeteritum: 'besuchte', perfekt: 'hat besucht', uk: 'відвідувати', en: 'to visit', hu: 'látogatni' },
    { infinitiv: 'aufmachen', praeteritum: 'machte auf', perfekt: 'hat aufgemacht', uk: 'відкривати', en: 'to open', hu: 'kinyitni' },
    { infinitiv: 'zumachen', praeteritum: 'machte zu', perfekt: 'hat zugemacht', uk: 'закривати', en: 'to close', hu: 'becsuknni' },
    { infinitiv: 'mitbringen', praeteritum: 'brachte mit', perfekt: 'hat mitgebracht', uk: 'принести з собою', en: 'to bring along', hu: 'elhozni' },
    { infinitiv: 'mitkommen', praeteritum: 'kam mit', perfekt: 'ist mitgekommen', uk: 'приходити разом', en: 'to come along', hu: 'eljönni' },
    { infinitiv: 'fernsehen', praeteritum: 'sah fern', perfekt: 'hat ferngesehen', uk: 'дивитися ТБ', en: 'to watch TV', hu: 'tévézni' },
    { infinitiv: 'nachdenken', praeteritum: 'dachte nach', perfekt: 'hat nachgedacht', uk: 'роздумувати', en: 'to think over', hu: 'elgondolkodni' },
    { infinitiv: 'aufhören', praeteritum: 'hörte auf', perfekt: 'hat aufgehört', uk: 'припиняти', en: 'to stop', hu: 'abbahagyni' },
    { infinitiv: 'anfangen', praeteritum: 'fing an', perfekt: 'hat angefangen', uk: 'починати', en: 'to start', hu: 'elkezdeni' },
    { infinitiv: 'ausgehen', praeteritum: 'ging aus', perfekt: 'ist ausgegangen', uk: 'виходити', en: 'to go out', hu: 'kijönni' },
    { infinitiv: 'einschlafen', praeteritum: 'schlief ein', perfekt: 'ist eingeschlafen', uk: 'засинати', en: 'to fall asleep', hu: 'elaludni' },
    { infinitiv: 'aufwachen', praeteritum: 'wachte auf', perfekt: 'ist aufgewacht', uk: 'прокидатися', en: 'to wake up', hu: 'felébredni' },
    { infinitiv: 'umziehen', praeteritum: 'zog um', perfekt: 'ist umgezogen', uk: 'переїжджати', en: 'to move house', hu: 'költözni' },
    { infinitiv: 'zurückkommen', praeteritum: 'kam zurück', perfekt: 'ist zurückgekommen', uk: 'повертатися', en: 'to come back', hu: 'visszajönni' },
    { infinitiv: 'weggehen', praeteritum: 'ging weg', perfekt: 'ist weggegangen', uk: 'іти геть', en: 'to leave/go away', hu: 'elmenni' },
    { infinitiv: 'weitermachen', praeteritum: 'machte weiter', perfekt: 'hat weitergemacht', uk: 'продовжувати', en: 'to continue', hu: 'folytatni' },
    { infinitiv: 'kennenlernen', praeteritum: 'lernte kennen', perfekt: 'hat kennengelernt', uk: 'познайомитися', en: 'to get to know', hu: 'megismerni' },
    { infinitiv: 'aufräumen', praeteritum: 'räumte auf', perfekt: 'hat aufgeräumt', uk: 'прибирати', en: 'to tidy up', hu: 'rendet rakni' },
    { infinitiv: 'einkaufen', praeteritum: 'kaufte ein', perfekt: 'hat eingekauft', uk: 'робити покупки', en: 'to go shopping', hu: 'bevásárolni' },
    { infinitiv: 'zuhören', praeteritum: 'hörte zu', perfekt: 'hat zugehört', uk: 'слухати', en: 'to listen', hu: 'meghallgatni' },
    { infinitiv: 'antworten', praeteritum: 'antwortete', perfekt: 'hat geantwortet', uk: 'відповідати', en: 'to answer', hu: 'válaszolni' },
    { infinitiv: 'fragen', praeteritum: 'fragte', perfekt: 'hat gefragt', uk: 'питати', en: 'to ask', hu: 'kérdezni' },
    { infinitiv: 'meinen', praeteritum: 'meinte', perfekt: 'hat gemeint', uk: 'мати на увазі', en: 'to mean', hu: 'gondolni vmit' },
    { infinitiv: 'glauben', praeteritum: 'glaubte', perfekt: 'hat geglaubt', uk: 'вірити', en: 'to believe', hu: 'hinni' },
    { infinitiv: 'hoffen', praeteritum: 'hoffte', perfekt: 'hat gehofft', uk: 'сподіватися', en: 'to hope', hu: 'reménykedni' },
    { infinitiv: 'wünschen', praeteritum: 'wünschte', perfekt: 'hat gewünscht', uk: 'бажати', en: 'to wish', hu: 'kívánni' },
    { infinitiv: 'suchen', praeteritum: 'suchte', perfekt: 'hat gesucht', uk: 'шукати', en: 'to search', hu: 'keresni' },
    { infinitiv: 'brauchen', praeteritum: 'brauchte', perfekt: 'hat gebraucht', uk: 'потребувати', en: 'to need', hu: 'szükséglik' },
    { infinitiv: 'bleiben', praeteritum: 'blieb', perfekt: 'ist geblieben', uk: 'залишатися', en: 'to stay', hu: 'maradni' },
    { infinitiv: 'hängen', praeteritum: 'hing', perfekt: 'hat gehangen', uk: 'висіти', en: 'to hang', hu: 'lógni' },
    { infinitiv: 'ziehen', praeteritum: 'zog', perfekt: 'hat gezogen', uk: 'тягнути', en: 'to pull', hu: 'húzni' },
    { infinitiv: 'werfen', praeteritum: 'warf', perfekt: 'hat geworfen', uk: 'кидати', en: 'to throw', hu: 'dobni' },
    { infinitiv: 'singen', praeteritum: 'sang', perfekt: 'hat gesungen', uk: 'співати', en: 'to sing', hu: 'énekelni' },
    { infinitiv: 'lassen', praeteritum: 'ließ', perfekt: 'hat gelassen', uk: 'дозволяти/лишати', en: 'to let/leave', hu: 'hagyni' },
    { infinitiv: 'stehlen', praeteritum: 'stahl', perfekt: 'hat gestohlen', uk: 'красти', en: 'to steal', hu: 'lopni' },
    { infinitiv: 'sterben', praeteritum: 'starb', perfekt: 'ist gestorben', uk: 'вмирати', en: 'to die', hu: 'meghalni' },
    { infinitiv: 'nennen', praeteritum: 'nannte', perfekt: 'hat genannt', uk: 'називати', en: 'to name', hu: 'nevezni' },
    { infinitiv: 'erfahren', praeteritum: 'erfuhr', perfekt: 'hat erfahren', uk: 'дізнаватися', en: 'to find out', hu: 'megtudni' },
];

// ─── B1: складніші та абстрактніші дієслова ───
window.WORDS_B1 = [
    { infinitiv: 'behaupten', praeteritum: 'behauptete', perfekt: 'hat behauptet', uk: 'стверджувати', en: 'to claim', hu: 'állítani' },
    { infinitiv: 'überzeugen', praeteritum: 'überzeugte', perfekt: 'hat überzeugt', uk: 'переконувати', en: 'to convince', hu: 'meggyőzni' },
    { infinitiv: 'beschreiben', praeteritum: 'beschrieb', perfekt: 'hat beschrieben', uk: 'описувати', en: 'to describe', hu: 'leírni' },
    { infinitiv: 'vergleichen', praeteritum: 'verglich', perfekt: 'hat verglichen', uk: 'порівнювати', en: 'to compare', hu: 'összehasonlítani' },
    { infinitiv: 'entwickeln', praeteritum: 'entwickelte', perfekt: 'hat entwickelt', uk: 'розвивати', en: 'to develop', hu: 'fejleszteni' },
    { infinitiv: 'verbessern', praeteritum: 'verbesserte', perfekt: 'hat verbessert', uk: 'покращувати', en: 'to improve', hu: 'javítani' },
    { infinitiv: 'erinnern', praeteritum: 'erinnerte', perfekt: 'hat erinnert', uk: 'нагадувати', en: 'to remind', hu: 'emlékeztetni' },
    { infinitiv: 'sich erinnern', praeteritum: 'erinnerte sich', perfekt: 'hat sich erinnert', uk: 'пам\'ятати', en: 'to remember', hu: 'emlékezni' },
    { infinitiv: 'vorbereiten', praeteritum: 'bereitete vor', perfekt: 'hat vorbereitet', uk: 'готуватися', en: 'to prepare', hu: 'felkészülni' },
    { infinitiv: 'ablehnen', praeteritum: 'lehnte ab', perfekt: 'hat abgelehnt', uk: 'відмовляти', en: 'to refuse', hu: 'visszautasítani' },
    { infinitiv: 'zustimmen', praeteritum: 'stimmte zu', perfekt: 'hat zugestimmt', uk: 'погоджуватися', en: 'to agree', hu: 'beleegyezni' },
    { infinitiv: 'widersprechen', praeteritum: 'widersprach', perfekt: 'hat widersprochen', uk: 'суперечити', en: 'to contradict', hu: 'ellentmondani' },
    { infinitiv: 'diskutieren', praeteritum: 'diskutierte', perfekt: 'hat diskutiert', uk: 'дискутувати', en: 'to discuss', hu: 'vitatkozni' },
    { infinitiv: 'berichten', praeteritum: 'berichtete', perfekt: 'hat berichtet', uk: 'повідомляти', en: 'to report', hu: 'beszámolni' },
    { infinitiv: 'vorschlagen', praeteritum: 'schlug vor', perfekt: 'hat vorgeschlagen', uk: 'пропонувати', en: 'to suggest', hu: 'javasolni' },
    { infinitiv: 'erreichen', praeteritum: 'erreichte', perfekt: 'hat erreicht', uk: 'досягати', en: 'to reach/achieve', hu: 'elérni' },
    { infinitiv: 'erlauben', praeteritum: 'erlaubte', perfekt: 'hat erlaubt', uk: 'дозволяти', en: 'to allow', hu: 'engedélyezni' },
    { infinitiv: 'verbieten', praeteritum: 'verbot', perfekt: 'hat verboten', uk: 'забороняти', en: 'to forbid', hu: 'megtiltani' },
    { infinitiv: 'bedeuten', praeteritum: 'bedeutete', perfekt: 'hat bedeutet', uk: 'означати', en: 'to mean', hu: 'jelenteni' },
    { infinitiv: 'gehören', praeteritum: 'gehörte', perfekt: 'hat gehört', uk: 'належати', en: 'to belong to', hu: 'tartozni' },
    { infinitiv: 'entstehen', praeteritum: 'entstand', perfekt: 'ist entstanden', uk: 'виникати', en: 'to arise', hu: 'keletkezni' },
    { infinitiv: 'bestehen', praeteritum: 'bestand', perfekt: 'hat bestanden', uk: 'існувати/скласти', en: 'to exist/pass', hu: 'fennállni/teljesíteni' },
    { infinitiv: 'aufgeben', praeteritum: 'gab auf', perfekt: 'hat aufgegeben', uk: 'здаватися', en: 'to give up', hu: 'feladni' },
    { infinitiv: 'durchführen', praeteritum: 'führte durch', perfekt: 'hat durchgeführt', uk: 'проводити', en: 'to carry out', hu: 'végrehajtani' },
    { infinitiv: 'lösen', praeteritum: 'löste', perfekt: 'hat gelöst', uk: 'вирішувати', en: 'to solve', hu: 'megoldani' },
    { infinitiv: 'sich beschweren', praeteritum: 'beschwerte sich', perfekt: 'hat sich beschwert', uk: 'скаржитися', en: 'to complain', hu: 'panaszkodni' },
    { infinitiv: 'vermissen', praeteritum: 'vermisste', perfekt: 'hat vermisst', uk: 'сумувати за', en: 'to miss', hu: 'hiányolni' },
    { infinitiv: 'sich freuen', praeteritum: 'freute sich', perfekt: 'hat sich gefreut', uk: 'радіти', en: 'to be happy', hu: 'örülni' },
    { infinitiv: 'sich ärgern', praeteritum: 'ärgerte sich', perfekt: 'hat sich geärgert', uk: 'злитися', en: 'to be annoyed', hu: 'bosszankodni' },
    { infinitiv: 'sich kümmern', praeteritum: 'kümmerte sich', perfekt: 'hat sich gekümmert', uk: 'піклуватися', en: 'to take care of', hu: 'gondoskodni' },
    { infinitiv: 'interessieren', praeteritum: 'interessierte', perfekt: 'hat interessiert', uk: 'цікавити', en: 'to interest', hu: 'érdekelni' },
    { infinitiv: 'unterstützen', praeteritum: 'unterstützte', perfekt: 'hat unterstützt', uk: 'підтримувати', en: 'to support', hu: 'támogatni' },
    { infinitiv: 'verändern', praeteritum: 'veränderte', perfekt: 'hat verändert', uk: 'змінювати', en: 'to change', hu: 'megváltoztatni' },
    { infinitiv: 'sich verändern', praeteritum: 'veränderte sich', perfekt: 'hat sich verändert', uk: 'мінятися', en: 'to change', hu: 'megváltozni' },
    { infinitiv: 'beeinflussen', praeteritum: 'beeinflusste', perfekt: 'hat beeinflusst', uk: 'впливати', en: 'to influence', hu: 'befolyásolni' },
    { infinitiv: 'herausfinden', praeteritum: 'fand heraus', perfekt: 'hat herausgefunden', uk: 'з\'ясовувати', en: 'to find out', hu: 'kideríteni' },
    { infinitiv: 'ausdrücken', praeteritum: 'drückte aus', perfekt: 'hat ausgedrückt', uk: 'виражати', en: 'to express', hu: 'kifejezni' },
    { infinitiv: 'teilnehmen', praeteritum: 'nahm teil', perfekt: 'hat teilgenommen', uk: 'брати участь', en: 'to participate', hu: 'részt venni' },
    { infinitiv: 'abhängen', praeteritum: 'hing ab', perfekt: 'hat abgehangen', uk: 'залежати', en: 'to depend on', hu: 'függeni' },
    { infinitiv: 'erkennen', praeteritum: 'erkannte', perfekt: 'hat erkannt', uk: 'розпізнавати', en: 'to recognize', hu: 'felismerni' },
    { infinitiv: 'feststellen', praeteritum: 'stellte fest', perfekt: 'hat festgestellt', uk: 'встановлювати', en: 'to determine', hu: 'megállapítani' },
    { infinitiv: 'umgehen mit', praeteritum: 'ging um', perfekt: 'ist umgegangen', uk: 'поводитися з', en: 'to deal with', hu: 'bánni vmivel' },
    { infinitiv: 'anbieten', praeteritum: 'bot an', perfekt: 'hat angeboten', uk: 'пропонувати', en: 'to offer', hu: 'felajánlani' },
    { infinitiv: 'achten auf', praeteritum: 'achtete auf', perfekt: 'hat geachtet', uk: 'звертати увагу', en: 'to pay attention', hu: 'figyelni' },
    { infinitiv: 'vertrauen', praeteritum: 'vertraute', perfekt: 'hat vertraut', uk: 'довіряти', en: 'to trust', hu: 'bízni' },
    { infinitiv: 'schützen', praeteritum: 'schützte', perfekt: 'hat geschützt', uk: 'захищати', en: 'to protect', hu: 'megvédeni' },
    { infinitiv: 'einsetzen', praeteritum: 'setzte ein', perfekt: 'hat eingesetzt', uk: 'використовувати', en: 'to use/deploy', hu: 'alkalmazni' },
    { infinitiv: 'bemerken', praeteritum: 'bemerkte', perfekt: 'hat bemerkt', uk: 'помічати', en: 'to notice', hu: 'észrevenni' },
    { infinitiv: 'verlangen', praeteritum: 'verlangte', perfekt: 'hat verlangt', uk: 'вимагати', en: 'to demand', hu: 'követelni' },
    { infinitiv: 'zweifeln', praeteritum: 'zweifelte', perfekt: 'hat gezweifelt', uk: 'сумніватися', en: 'to doubt', hu: 'kételkedni' },
];

// ALL = A1 + A2 + B1
window.WORDS_ALL = [...window.WORDS_A1, ...window.WORDS_A2, ...window.WORDS_B1];